### ISSUE TITLE
Hi, i need to ask you to run cmder inside intelli..

### ISSUE THREAD

**Issue by realsby** [bryanjhv/laravel-blade-cdn#1]
You said : Note that you should have ansi_code_support = 1 in config\settings file in order to correctly display ASCII escapes (colors, etc).
Otherwise you'll get this nice prompt

where should i set ansi_code_support ? inside cmder or pycharm i dont get it.

**Comment by bryanjhv** [comment]
Open Cmder and type `explorer %CMDER_ROOT%`, a folder is opened in your Explorer where you can find a `config` folder with a `settings` file inside it.

> Next time, comment where my comment was or email me, this is NOT related to this project.
